variables:
  # This job runs fine with the amd64-runner defaults (storage is probably over-specified)
  #KUBERNETES_CPU_REQUEST: 2
  #KUBERNETES_MEMORY_REQUEST: 4G
  #KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 20G
  PROJECT_ID: 62615
  REF_NAME: master

test:
  stage: test
  image: debian:bookworm-slim
  tags:
    - amd64-runner
  parallel:
    matrix:
      - ARCH: arm
        CROSS_COMPILE:
          - ${CI_BUILDS_DIR}/kgdbtest/buildroot/arm/host/bin/arm-linux-
      - ARCH: arm64
        CROSS_COMPILE:
          - ${CI_BUILDS_DIR}/kgdbtest/buildroot/arm64/host/bin/aarch64-linux-
      - ARCH: mips
        CROSS_COMPILE:
          - ${CI_BUILDS_DIR}/kgdbtest/buildroot/mips/host/bin/mips64el-linux-
      - ARCH: riscv
        CROSS_COMPILE:
          - ${CI_BUILDS_DIR}/kgdbtest/buildroot/riscv/host/bin/riscv64-linux-
      - ARCH: x86
  script:
    - apt-get update && apt-get -y upgrade
    - apt-get install -y bison bc build-essential cpio flex gdb git libelf-dev libncurses-dev libssl-dev picocom python3-pexpect python3-pytest qemu-system-arm qemu-system-misc qemu-system-mips qemu-system-x86 socat wget xz-utils zstd
    - git clone https://git.codelinaro.org/daniel.thompson/kgdbtest.git -b ${REF_NAME} ${CI_BUILDS_DIR}/kgdbtest
    - wget -O buildroot-${ARCH}.tar.zst https://git.codelinaro.org/api/v4/projects/${PROJECT_ID}/jobs/artifacts/${REF_NAME}/raw/buildroot-${ARCH}.tar.zst?job=build-${ARCH}
    - tar -C ${CI_BUILDS_DIR}/kgdbtest -xf buildroot-${ARCH}.tar.zst
    - make -C ${CI_BUILDS_DIR}/kgdbtest kdmx
    - PYTEST_EXTRAFLAGS=--junit-xml=${PWD}/results.xml make -C ${CI_BUILDS_DIR}/kgdbtest V=2
  artifacts:
    paths:
      - results.xml
    reports:
      junit: results.xml
